"""Generate platform-specific manifests from SKILL.md files.

Usage:
    vespaskills generate          # Generate all artifacts
    vespaskills generate --check  # Validate artifacts are up-to-date (CI mode)
"""

import glob
import json
import os
import re
import sys

from vespaskills.logger import get_logger

logger = get_logger()

ROOT = os.getcwd()

EXCLUDE_DIRS = {"node_modules", ".git", ".claude", ".claude-plugin", ".cursor-plugin"}


def parse_frontmatter(path: str) -> dict:
    """Parse YAML frontmatter from a SKILL.md file. Handles simple key: value pairs."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if not text.startswith("---"):
        raise ValueError(f"{path}: missing YAML frontmatter")
    end = text.index("---", 3)
    meta = {}
    for line in text[3:end].strip().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition(":")
        value = value.strip().strip('"').strip("'")
        meta[key.strip()] = value
    meta["_body"] = text[end + 3 :].strip()
    meta["_path"] = path
    return meta


def discover_skills() -> list[dict]:
    """Find all */SKILL.md files and parse their frontmatter."""
    skills = []
    for path in sorted(glob.glob(os.path.join(ROOT, "*/SKILL.md"))):
        dirname = os.path.basename(os.path.dirname(path))
        if dirname in EXCLUDE_DIRS:
            continue
        meta = parse_frontmatter(path)
        meta["_dir"] = dirname
        skills.append(meta)
    return skills


AGENTS_TEMPLATE = """\
# Vespa Skills — Agent Instructions

> Auto-generated by `generate.py`. Do not edit manually.

This repository contains AI coding-assistant skills for **Vespa.ai**.
Each skill is a self-contained folder with a `SKILL.md` file as the primary reference.

## Available Skills

{skill_sections}

## How to Use

1. Read the relevant `SKILL.md` for the task at hand.
2. Load files from the `docs/` folder when you need deeper reference detail.
3. Combine skills as needed — e.g., use **schema-authoring** to define the schema,
   **app-package** to set up services.xml, **query-builder** for rank profiles, and
   **feed-operations** to populate data.

## Reference

- Vespa documentation: https://docs.vespa.ai
- Vespa GitHub: https://github.com/vespa-engine/vespa
- Sample applications: https://github.com/vespa-engine/sample-apps
"""


def generate_agents_md(skills: list[dict]) -> str:
    sections = []
    for s in skills:
        docs_dir = os.path.join(ROOT, s["_dir"], "docs")
        doc_files = []
        if os.path.isdir(docs_dir):
            doc_files = sorted(f"docs/{f}" for f in os.listdir(docs_dir) if f.endswith(".md"))
        docs_line = ""
        if doc_files:
            items = ", ".join(f"`{d}`" for d in doc_files)
            docs_line = f"\n- Reference docs: {items}"
        sections.append(
            f"### {s.get('name', s['_dir'])}\n\n"
            f"- Path: `{s['_dir']}/SKILL.md`\n"
            f"- {s.get('description', 'No description')}"
            f"{docs_line}"
        )
    return AGENTS_TEMPLATE.format(skill_sections="\n\n".join(sections))


def validate_marketplace(skills: list[dict]) -> list[str]:
    marketplace_path = os.path.join(ROOT, ".claude-plugin", "marketplace.json")
    if not os.path.exists(marketplace_path):
        return [".claude-plugin/marketplace.json not found"]

    with open(marketplace_path, encoding="utf-8") as f:
        marketplace = json.load(f)

    mp_names = {entry["name"] for entry in marketplace.get("plugins", [])}
    skill_names = {s.get("name", s["_dir"]) for s in skills}

    errors = []
    for name in skill_names - mp_names:
        errors.append(f"Skill '{name}' missing from .claude-plugin/marketplace.json")
    for name in mp_names - skill_names:
        errors.append(f"Marketplace entry '{name}' has no matching SKILL.md")
    return errors


BEGIN_MARKER = "<!-- SKILLS:BEGIN -->"
END_MARKER = "<!-- SKILLS:END -->"


def generate_skills_table(skills: list[dict]) -> str:
    lines = [
        BEGIN_MARKER,
        "| Skill | Description |",
        "|-------|-------------|",
    ]
    for s in skills:
        name = s.get("name", s["_dir"])
        desc = s.get("description", "")
        lines.append(f"| [`{name}`]({s['_dir']}/SKILL.md) | {desc} |")
    lines.append(END_MARKER)
    return "\n".join(lines)


def update_readme(skills: list[dict]) -> str | None:
    readme_path = os.path.join(ROOT, "README.md")
    if not os.path.exists(readme_path):
        return None
    with open(readme_path, encoding="utf-8") as f:
        content = f.read()
    if BEGIN_MARKER not in content:
        return None

    table = generate_skills_table(skills)
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    return pattern.sub(table, content)


def write_if_changed(path: str, content: str) -> bool:
    """Write content to path if it differs from current contents."""
    rel = os.path.relpath(path, ROOT)
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            if f.read() == content:
                logger.info(f"  {rel} (unchanged)")
                return False
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.success(f"  {rel} (updated)")
    return True


def run(args):
    """Run generate command with parsed args."""
    check_mode = args.check

    skills = discover_skills()
    if not skills:
        logger.error("No skills found (no */SKILL.md files)")
        sys.exit(1)

    logger.info(f"Found {len(skills)} skill(s): {', '.join(s.get('name', s['_dir']) for s in skills)}")

    errors = validate_marketplace(skills)
    if errors:
        for e in errors:
            logger.error(e)
        sys.exit(1)

    agents_md = generate_agents_md(skills)
    readme_content = update_readme(skills)

    if check_mode:
        logger.info("Running in --check mode (validating, not writing)...")
        drift = False

        agents_path = os.path.join(ROOT, "AGENTS.md")
        rel = os.path.relpath(agents_path, ROOT)
        if not os.path.exists(agents_path):
            logger.warning(f"  DRIFT: {rel} does not exist")
            drift = True
        else:
            with open(agents_path, encoding="utf-8") as f:
                if f.read() != agents_md:
                    logger.warning(f"  DRIFT: {rel} is out of date")
                    drift = True
                else:
                    logger.success(f"  OK: {rel}")

        if readme_content is not None:
            readme_path = os.path.join(ROOT, "README.md")
            with open(readme_path, encoding="utf-8") as f:
                if f.read() != readme_content:
                    logger.warning("  DRIFT: README.md skills table is out of date")
                    drift = True
                else:
                    logger.success("  OK: README.md")

        if drift:
            logger.error("Drift detected. Run 'vespaskills generate' to fix.")
            sys.exit(1)
        else:
            logger.success("All artifacts are up to date.")
            sys.exit(0)
    else:
        logger.info("Generating artifacts...")
        write_if_changed(os.path.join(ROOT, "AGENTS.md"), agents_md)
        if readme_content is not None:
            write_if_changed(os.path.join(ROOT, "README.md"), readme_content)
        logger.success("Done.")
